import {
  Bot,
  Briefcase,
  Building2,
  CircleDollarSign,
  Code2,
  Gamepad2,
  Globe,
  GraduationCap,
  HeartPulse,
  Home,
  ListChecks,
  MapPin,
  Megaphone,
  Mic,
  MoreHorizontal,
  Newspaper,
  Palette,
  PenLine,
  Plane,
  Rocket,
  Scale,
  Search,
  Share2,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  TrendingUp,
  Trophy,
  User,
  UtensilsCrossed,
  type LucideIcon,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  "seo-ai-visibility": Search,
  "ai-agents-infra": Bot,
  "ai-content-generation": Sparkles,
  "marketing-advertising": Megaphone,
  "developer-tools": Code2,
  "productivity-personal": ListChecks,
  "design-creative": Palette,
  "social-creator-tools": Share2,
  "writing-content": PenLine,
  "sales-lead-gen": TrendingUp,
  "business-finance-legal": Scale,
  "education-learning": GraduationCap,
  "health-fitness": HeartPulse,
  "directories-launch": Rocket,
  "hiring-jobs": Briefcase,
  "agencies-services": Building2,
  "media-news": Newspaper,
  "real-estate": Home,
  "study-abroad": Plane,
  "food-restaurants": UtensilsCrossed,
  "people-profiles": User,
  "games-entertainment": Gamepad2,
  "ecommerce-retail": ShoppingCart,
  "audio-voice-podcasting": Mic,
  "security-privacy-compliance": ShieldCheck,
  "domains-web-assets": Globe,
  "leaderboards-attention": Trophy,
  "travel-local-lifestyle": MapPin,
  "web3-investing": CircleDollarSign,
};

export const DEFAULT_CATEGORY_ICON: LucideIcon = MoreHorizontal;
